### ISSUE TITLE
Public forum

### ISSUE THREAD

**Issue by taiya** [ataiya/igd#1]
Please use this public forum to post any question related to the course.
However, be careful not to post anything that might give away the solution of an assignment!
When in doubt, email the TA (Raghu).

**Comment by jonhealy1** [comment]
Has anyone else had problems using their key card to get into the lab room, ECS 354?

**Comment by connerleverett** [comment]
@noonespecial009 I had this problem today. I sent an email to engrcard@engr.uvic.ca from my UVic email address, stated my name, student number, card number (on the top right corner of the card) and what room I needed access to and why. They emailed me back on the same day and activated my key card.

**Comment by jonhealy1** [comment]
Hi Conner. I emailed this address too and got mine straightened out. Thank you.

**Comment by ehedlin** [comment]
I have a couple questions regarding the 205 assignment. Are we supposed to have just 1 level or many? Also I was wondering if we are allowed to make our own sprites instead of using the ones from the asset store?

**Comment by r4ghu** [comment]
Hi @ehedlin,  
For getting full score in the assignment, you need to complete just 1 level. But you are free to work on as many levels as you want. Regarding the sprites, please note that this is not a design oriented course. You can create your own sprites if time permits but it is not mandatory. The resources for sprites and audio are well documented in the wiki page. Anyone who uses them, please do give credits to the sources in the Menu->About page of your game.

**Comment by masonrg** [comment]
For the recommended components of the assignment it says to implement our own physics and collisions. So this would mean not using rigidbodies or colliders at all?

**Comment by taiya** [comment]
@MasonRG do you mind opening a new issue? :)
This post was just a placeholder

**Comment by taiya** [comment]
@MasonRG for a reply to your question, see Issue #3
