### ISSUE TITLE
Quaternion multiplication: bonus 1%

### ISSUE THREAD

**Issue by taiya** [ataiya/igd#11]
Express a quaternion multiplication between these quaternions using only vec3/float operations (multiplications, dot products, ...), where v and w are vec3:
```
q1 = ai + bj + ck + d = [v, d]
q2 = ei + fj + gk + h = [w, h]
```

Only the first **correct** answer will be awarded the bonus point.
The solution will be presented in the next lecture.

**Comment by ben4num** [comment]
|    | ai   | bj   | ck   | D   |
|----|------|------|------|-----|
| ei | aeii | beji | ceki | Dei |
| gj | agij | bgjj | cgkj | Dgj |
| hk | ahik | bhjk | chkk | Dhk |
| K  | aKi  | bKj  | cKk  | DK  |


k = ij, i = jk, j=ki
-k = ji, -i = kj, -j=ik

Sum = DK - ae - bg - ch +
-bek + cej + Dei +
agk + -cgi + Dgj +
-ahj + bhi + Dhk +
aKi + bKj + cKk +


Sum = DK - ae - bg - ch +
(De -cg + bh + aK)i
(ce + Dg -ah + bK)j
(-be +ag + Dh + cK)k

DK - ae - bg - ch = DK - (v dot w)
beji + ceki + cgkj + agij + ahik + bhjk = (v cross w) (cross product cancels negative signs)
Dei + Dgj + Dhk = D(w)
aKi + bKj + cKk = K(v)

d(w) + h(v) + dh + (v dot w) + (v cross w) = Product
(v,d)(w,h) = (dw + hv + (v cross w), dh - (v dot w))

Equivalent to Rotation by (ai + bj + ck + D) followed by (ei + gj + hk + K)

**Comment by taiya** [comment]
@behnamx good, but that's incomplete.
This is raw! You are supposed to use vec3 math, not just raw float*float operations :)

**Comment by behnamx** [comment]
q1 = ai + bj + ck + d = [v, d]
q2 = ei + fj + gk + h = [w, h]

d(w) + h(v) + dh + (v dot w) + (beji + ceki + cfkj + afij + agik + bgjk) = cross product  - from before
(v,d)(w,h) = (dh - (v dot w), dw + hv + (v cross w))

**Comment by ben4num** [comment]
updated
