### ISSUE TITLE
Phase 1 of final project

### ISSUE THREAD

**Issue by jonhealy1** [ataiya/igd#14]
It says that **phase 1** of the final project is due on March 14th. but we are not given any information on what phase 1 entails besides for the brief description, 'project design and end goal'. How does this work exactly? Is it a report that is due? Thank you.

**Comment by taiya** [comment]
The intermediate reports are just to help you keep track of the project and start early. Essentially what we are asking you to do, is **decide what your game will be by next week**. In this way the TA can provide feedback if you happen to do something too complex or too easy, for example.

**Comment by jonhealy1** [comment]
Oh ok awesome. Thanks.

**Comment by danielfrankcom** [comment]
It looks like something went wrong with the Connex submission? I think everyone is all in one group, so not sure if we can submit documents without overwriting other's changes.

**Comment by taiya** [comment]
I'll have @r4ghu look into this. Meanwhile, send your PDF to him by email.
