### ISSUE TITLE
Final Project: Animation component.

### ISSUE THREAD

**Issue by jonhealy1** [ataiya/igd#16]
Hi. I am wondering what the expectations for the Animation component are. Are we expected to handle animations with code or with the Unity animator? I know we are covering animation now this week but I have been learning the animator in Unity and am wondering if I should continue? Also, could you go into some detail regarding what constitutes say the difference between meeting or exceeding expectations regarding animation.

**Comment by taiya** [comment]
Hello there!

Note you don't have to do every topic for the breadth requirement.
And yes, It's perfectly fine for you to keep going on your Unity/animator feature.

We haven't done an assignment on animation, thus the requirements are a bit more lax.
Meeting would be to just re-deploy what you have seen in the lab, while exceeding would be investigating something independently which we haven't shown you how to do.
