### ISSUE TITLE
Report 3

### ISSUE THREAD

**Issue by KrisHurworth** [ataiya/igd#19]
On the hw03_Project page it states that our final report and gameplay video are due on the 11th but the demos aren't until the 13th, are the report and video not meant to be due on the same day as the demo? If we are still going to be working on our project right until the very end to keep making it better are we able to submit the gameplay video on the 13th with the demo instead of on the 11th?

**Comment by taiya** [comment]
Yes it's fine to submit the video on the 13th (the report is strict on the 11th, as we read it beforehand)

**Comment by KrisHurworth** [comment]
In that case how would you like us to show you the videos? On the page it states we should put the link to our video on our report. Should we just email the gameplay video link to you if we decide to submit it on the 13th?

**Comment by taiya** [comment]
Hi Kris, you can insert a preliminary video in the report, and provide a second link on demo day.
