### ISSUE TITLE
Working on game after the project report is due. 

### ISSUE THREAD

**Issue by jonhealy1** [ataiya/igd#20]
Hi.

The final report is due on Tuesday and the live demos of our games are on Thursday however we plan to be adding new features to our game right up until late Tuesday and Wednesday night and we don't know how much we will accomplish in those last two days. Definitely though we will be attempting to add icing to the cake so to speak and propel our project to exceed expectations. Would it make more sense to have the reports due on Thursday as well?

Thanks.

**Comment by taiya** [comment]
No, the **reports are due on the advertised date** as we like to be prepared to ask appropriate questions during the demo. 

That doesn’t mean that you cannot add features to it and tweak your report to include this new material (as additional material). This is exactly what I did two weeks ago for an ICCV (international conference on computer vision) paper submission.
