### ISSUE TITLE
Final Project Submission

### ISSUE THREAD

**Issue by kariewas** [ataiya/igd#21]
Hi,

When and where are we supposed to submit each component of the final project?

**Comment by taiya** [comment]
Report + video link are due as advertised on the connex assignment page. If you decide to improve your report after due date (e.g. a new feature was implemented in the last two days) make sure you highlight the changes (in red ink) in the PDF report.

**Comment by kariewas** [comment]
So all due dates times are midnight?
Will there be a link on connex where we submit each component? Or should we just email them to you?

**Comment by taiya** [comment]
Yes, the TA @r4ghu will create the submission entry on connex soon.
