### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by kariewas** [ataiya/igd#23]
Since we are allowed to continue working on our project after the report gets handed in, is it possible to extend the due date for submitting the source code to Thursday? Also, are there any specific requirements for the source code? There doesn't seem to be anything mentioned in the assignment description.

**Comment by taiya** [comment]
1) you can hand it in via USB to the TA on demo day
2) just ZIP the unity project folder and submit that?
(test you can re-load and execute the project on another machine, e.g. in the lab)
