### ISSUE TITLE
Public Forum

### ISSUE THREAD

**Issue by taiya** [ataiya/igd#27]
Please use this public forum to post any question related to the course. However, be careful not to post anything that might give away the solution of an assignment! When in doubt, email the TA.

**Comment by GFBryson** [comment]
does anyone know where the written class notes are being posted?

**Comment by taiya** [comment]
Link on homepage of connnex page

**Comment by Etherkavu** [comment]
Had a brain fart, which version of unity are we using in labs?

**Comment by taiya** [comment]
@Etherkavu I'd recommend you post a new issue about it (otherwise we risk not seeing messages in old threads)

**Comment by drebain** [comment]
The lab machines should have Unity 5.5 installed.
