### ISSUE TITLE
Question about physics in Hw1

### ISSUE THREAD

**Issue by taiya** [ataiya/igd#3]
> For the recommended components of the assignment it says to implement our own physics and collisions. So this would mean not using rigidbodies or colliders at all?

There is a full hierarchy of variants that can be implemented (easier to harder):
1) use unity internals
2) (version1) analytic solution of trajectories, but use UNITY colliders
2) (version2) use UNITY physics, but re-write your own colliders
3) use Verlet/Euler for numerical integration (but use UNITY colliders)
4) use numerical integration and write your own colliders

The harder the task, the more % points you get.

**Comment by masonrg** [comment]
Ok, that makes sense. Thanks.
