### ISSUE TITLE
Questions about the midterm

### ISSUE THREAD

**Issue by MikeRed** [ataiya/igd#5]
Hi Dr.Tagliasacchi, I have some questions about the midterm tomorrow:

1) Will there be any Unity syntax questions on the midterm?

2) Will we be tested on any of the guest lecture content?

3) In chapter 12.4 of the textbook, on page 696, the velocity Verlot method is used to determine velocity at a specific time. What I find confusing is that in step 3 of the algorithm, the third argument of the force function is v(t2). But isn't the purpose of the algorithm to calculate v(t2)? How can we use it in step 3 if we don't know what it is yet? 

Thanks!

**Comment by taiya** [comment]
1. no, just pseudocode is fine, e.g. mat4 m; m(i,j) = 1.0;
2. no, but the concepts behind shaders are covered
3. I suggest you to take a look at slide 41 of [this set](https://www.dropbox.com/s/0z2zwv21lzvmbqm/04_dynamics.key.pdf?dl=0) and re-derive the verlet formula by replacing the velocity estimate. If you still have problems, feel free to drop by my office tomorrow 

Cheers
